"""Holodeck's Librarian module: handle library generation and management.

Module Contents
---------------

* __init__.py
    - This is the root of the librarian module.

* combine.py
    - Combine individual simulation files (generated by _____) into a single library 'hdf5' file.

* fit_spectra.py
    - Perform fits to the GWB spectra in a library ('hdf5') file.

* gen_lib.py
    - Generate libraries by executing many simulations, typically in parallel, and typically from
    the command line.

* lib_utils.py
    - Utility methods for generating and managing libraries.

* param_spaces_classic.py
    - Definitions of parameter space classes (which inherit from :class:`_Param_Space`) that were
    used in the NANOGrav 15yr astrophysics interpretation analysis.

* params.py
    - Definitions of base classes for library generation, for example the :class:`_Param_Dist` and
    :class:`_Param_Space` base classes.

* posterior_populations.py
    - Generate populations by drawing from the posterior distributions of libraries fit against
    observational data.

"""


__version__ = "1.0"

DEF_NUM_REALS = 100
DEF_NUM_FBINS = 40
DEF_NUM_LOUDEST = 5
DEF_PTA_DUR = 16.03     # [yrs]

FITS_NBINS_PLAW = [3, 4, 5, 10, 15]
FITS_NBINS_TURN = [5, 10, 15]

FNAME_SIM_FILE = "sam-lib__p{pnum:06d}.npz"
PSPACE_FILE_SUFFIX = ".pspace.npz"

from . import params        # noqa
# from . param_spaces_classic import (   # noqa
#     PS_Classic_Phenom_Uniform,
#     PS_Classic_Phenom_Astro_Extended,
#     PS_Classic_GWOnly_Uniform,
#     PS_Classic_GWOnly_Astro_Extended,
# )

param_spaces = {}
from . import param_spaces_classic as psc  # noqa
param_spaces.update(psc._param_spaces)
del psc
