"""Tests for :mod:`holodeck.librarian.flows_lib`.

The load-bearing tests here are the ones that do not involve random numbers:

* :func:`test_loudest_per_bin_selection` pins the "which cell holds the l-th loudest binary"
  search against a brute-force reference, with the Poisson counts injected rather than drawn.
* :func:`test_rank_cws_matches_reference` pins the across-band ranking against a brute-force
  reference.

Everything downstream of those is deterministic, so if they hold, a library's contents are pinned.


** These tests are generated by Claude **

"""

import numpy as np
import pytest

import holodeck as holo
from holodeck import utils
from holodeck.constants import MSOL, MPC, YR
from holodeck.librarian import flows_lib


class _FakeRNG:
    """Stands in for a ``numpy.random.Generator``, returning pre-set counts instead of drawing.

    ``loudest_per_bin`` calls ``rng.poisson(lam, size=(R, B))`` once per frequency bin, in
    increasing bin order, so the counts are handed back in that order.
    """

    def __init__(self, counts_per_freq):
        self._counts = list(counts_per_freq)
        self._ii = 0

    def poisson(self, lam, size=None):
        out = np.asarray(self._counts[self._ii])
        self._ii += 1
        assert out.shape == size, f"injected counts {out.shape} != requested {size}"
        return out


def _brute_force_loudest(counts, h2, cell, nloudest):
    """Reference implementation: expand the counts into individual binaries and take the first N.

    ``counts``, ``h2``, and ``cell`` are all ordered loudest-first.
    """
    hc2 = np.repeat(h2, counts)[:nloudest]
    idx = np.repeat(cell, counts)[:nloudest]
    return hc2, idx


# ==============================================================================
# ====    loudest_per_bin    ====
# ==============================================================================


def test_loudest_per_bin_selection():
    """The l-th loudest binary must come from the cell a brute-force expansion puts it in."""
    # a (2, 2, 2) = 8-cell grid, 1 frequency bin, 4 realizations
    M, Q, Z, F = 2, 2, 2, 1
    R, L = 4, 3

    # strictly decreasing strain so the sort order is unambiguous; `number` is irrelevant to the
    # selection once the counts are injected, it only decides which cells are 'live'
    h2 = np.arange(8, 0, -1).astype(float).reshape(M, Q, Z, F)
    number = np.ones((M, Q, Z, F))

    # Counts cover the cases that matter, per realization:
    #   0: several bins hold one binary each
    #   1: the loudest cell alone holds more than `nloudest`
    #   2: leading cells are empty, so the search must walk past them
    #   3: fewer than `nloudest` binaries exist in the whole frequency bin
    counts = np.array([
        [1, 1, 1, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 2, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
    ])

    rng = _FakeRNG([counts])
    hc2ss, bidx, _ = flows_lib.loudest_per_bin(number, h2, R, L, rng)

    # cells are sorted loudest-first; with strictly decreasing h2 that is just flat order
    h2_sorted = h2.reshape(8, F)[:, 0]
    cell_sorted = np.arange(8)

    for rr in range(R):
        want_hc2, want_idx = _brute_force_loudest(counts[rr], h2_sorted, cell_sorted, L)
        n = len(want_hc2)
        assert np.array_equal(hc2ss[0, rr, :n], want_hc2), f"realization {rr}"
        assert np.array_equal(bidx[0, rr, :n], want_idx), f"realization {rr}"
        # slots beyond the available binaries stay empty
        assert np.all(hc2ss[0, rr, n:] == 0.0), f"realization {rr}"
        assert np.all(bidx[0, rr, n:] == -1), f"realization {rr}"


def test_loudest_per_bin_skips_dead_cells():
    """Cells with no binaries, or no strain, must never be selected."""
    M, Q, Z, F = 2, 2, 2, 1
    R, L = 2, 2

    h2 = np.arange(8, 0, -1).astype(float).reshape(M, Q, Z, F)
    number = np.ones((M, Q, Z, F))
    # kill the two loudest cells in two different ways
    number[0, 0, 0, 0] = 0.0     # no binaries expected here
    h2[0, 0, 1, 0] = 0.0         # no strain here

    # only 6 cells survive; the injected counts must match that width
    counts = np.array([[1, 1, 0, 0, 0, 0],
                       [0, 1, 1, 0, 0, 0]])
    rng = _FakeRNG([counts])
    hc2ss, bidx, _ = flows_lib.loudest_per_bin(number, h2, R, L, rng)

    dead = {0, 1}   # flat indices of the two cells killed above
    live_idx = bidx[bidx >= 0]
    assert not (set(live_idx.tolist()) & dead), "a dead cell was selected"
    assert np.all(hc2ss[bidx >= 0] > 0.0)


def test_loudest_per_bin_rest():
    """`hc2rest` must be exactly the strain-squared NOT carried by the extracted singles."""
    M, Q, Z, F = 2, 2, 2, 1
    R, L = 2, 2
    h2 = np.arange(8, 0, -1).astype(float).reshape(M, Q, Z, F)
    number = np.ones((M, Q, Z, F))
    counts = np.array([[3, 0, 1, 0, 0, 0, 0, 2],
                       [0, 1, 0, 0, 4, 0, 0, 0]])

    rng = _FakeRNG([counts])
    hc2ss, _bidx, hc2rest = flows_lib.loudest_per_bin(number, h2, R, L, rng, totals=True)
    h2_flat = h2.reshape(8, F)[:, 0]
    total = counts @ h2_flat
    assert np.allclose(hc2rest[0] + hc2ss[0].sum(axis=-1), total)


def test_loudest_per_bin_rest_is_exactly_zero():
    """When every binary is extracted, the background must be 0, not float noise.

    This is the case the sparse high-frequency bins are in, and it is why `hc2rest` is
    accumulated directly instead of as `total - sum(singles)`: that subtraction leaves a residue
    at ~1e-18 of the total, which is nonsense when the true answer is zero.
    """
    M, Q, Z, F = 2, 2, 2, 1
    R, L = 3, 10
    # strains spanning many orders of magnitude, so a subtraction would cancel badly
    h2 = np.logspace(-30, -50, 8).reshape(M, Q, Z, F)
    number = np.ones((M, Q, Z, F))
    # every realization holds fewer than `nloudest` binaries -> nothing left over
    counts = np.array([[1, 1, 1, 0, 0, 0, 0, 0],
                       [2, 0, 0, 0, 0, 1, 0, 0],
                       [0, 0, 0, 0, 0, 0, 0, 1]])

    rng = _FakeRNG([counts])
    hc2ss, _bidx, hc2rest = flows_lib.loudest_per_bin(number, h2, R, L, rng, totals=True)
    assert np.all(counts.sum(axis=1) <= L), "test setup: every binary must be extractable"
    assert np.array_equal(hc2rest[0], np.zeros(R)), f"expected exact zeros, got {hc2rest[0]}"


def test_loudest_per_bin_empty_frequency():
    """A frequency bin with no live cells must produce empty slots, not an error."""
    number = np.zeros((2, 2, 2, 2))
    h2 = np.ones((2, 2, 2, 2))
    number[..., 1] = 1.0     # only the second frequency has binaries

    counts = np.array([[1, 0, 0, 0, 0, 0, 0, 0]])
    rng = _FakeRNG([counts])       # called only once: the first frequency bin is skipped entirely
    hc2ss, bidx, _ = flows_lib.loudest_per_bin(number, h2, 1, 2, rng)

    assert np.all(bidx[0] == -1), "empty frequency bin produced a source"
    assert np.all(hc2ss[0] == 0.0)
    assert bidx[1, 0, 0] == 0, "populated frequency bin produced no source"


# ==============================================================================
# ====    rank_cws    ====
# ==============================================================================


def test_rank_cws_matches_reference():
    """Ranking across the band must match a brute-force sort of every candidate."""
    rng = np.random.default_rng(12345)
    F, R, L, K = 6, 5, 4, 7

    hc_ss = rng.uniform(1e-18, 1e-15, size=(F, R, L))
    bidx = rng.integers(0, 100, size=(F, R, L))
    # scatter some dead slots, including a realization with fewer than K live candidates
    bidx[hc_ss < 2e-16] = -1
    bidx[:, 0, :] = -1
    bidx[0, 0, 0] = 5

    fobs = np.arange(1, F + 1) * 1e-9

    for rankby in ['hc', 'resid']:
        got = flows_lib.rank_cws(hc_ss, bidx, fobs, nrank=K, rankby=rankby)
        stat = flows_lib.cw_rank_stat(hc_ss, fobs, rankby)

        for rr in range(R):
            # brute force: every (f, l) candidate of this realization, best first
            cands = [(stat[ff, rr, ll], ff, ll)
                     for ff in range(F) for ll in range(L) if bidx[ff, rr, ll] >= 0]
            cands.sort(key=lambda t: -t[0])
            nlive = min(K, len(cands))

            for kk in range(nlive):
                _s, ff, ll = cands[kk]
                assert got['fidx'][rr, kk] == ff, f"{rankby} r={rr} k={kk}"
                assert got['lidx'][rr, kk] == ll, f"{rankby} r={rr} k={kk}"
                assert got['hc'][rr, kk] == hc_ss[ff, rr, ll]
                assert got['bidx'][rr, kk] == bidx[ff, rr, ll]

            # any remaining slots are dead
            assert np.all(got['fidx'][rr, nlive:] == -1), f"{rankby} r={rr}"
            assert np.all(got['bidx'][rr, nlive:] == -1), f"{rankby} r={rr}"


def test_rank_cws_rejects_too_many():
    hc_ss = np.ones((2, 3, 4))
    bidx = np.zeros((2, 3, 4), dtype=int)
    fobs = np.array([1e-9, 2e-9])
    with pytest.raises(ValueError):
        flows_lib.rank_cws(hc_ss, bidx, fobs, nrank=9)


# ==============================================================================
# ====    cw_columns    ====
# ==============================================================================


def test_cw_columns_values_and_layout():
    """Columns must match the closed-form values, and land in (1, nrank, nreal)."""
    from holodeck import cosmo

    R, K = 3, 2
    M, Q, Z, F = 2, 2, 2, 3

    mt = np.array([1e8, 1e9]) * MSOL
    mr = np.array([0.3, 0.9])
    redz = np.full((M, Q, Z, F), 0.5)
    fobs = np.array([1e-9, 2e-9, 3e-9])

    # one source per (realization, rank), all live except the last, which is a dead slot
    bidx = np.arange(R * K).reshape(R, K) % (M * Q * Z)
    fidx = np.arange(R * K).reshape(R, K) % F
    lidx = np.zeros((R, K), dtype=int)
    hc = np.full((R, K), 1e-16)
    fidx[-1, -1] = -1

    ranked = dict(hc=hc, bidx=bidx, fidx=fidx, lidx=lidx)
    out = flows_lib.cw_columns(ranked, mt, mr, redz, fobs)

    for key in flows_lib.CW_KEYS + flows_lib.PROV_KEYS + flows_lib.IDX_KEYS:
        assert out[key].shape == (1, K, R), f"{key} has shape {out[key].shape}"

    mm, qq, _zz = np.unravel_index(bidx, (M, Q, Z))
    mtot, mrat = mt[mm], mr[qq]
    mchirp = mtot * mrat**(3/5) / (1 + mrat)**(6/5)
    want_mc = np.log10(mchirp * 1.5 / MSOL)
    want_dc = np.log10(np.asarray(cosmo.z_to_dcom(np.full((R, K), 0.5))) / MPC)
    want_fo = np.log10(fobs[np.where(fidx >= 0, fidx, 0)])

    live = fidx >= 0
    assert np.allclose(out['log10_mc'][0].T[live], want_mc[live])
    assert np.allclose(out['log10_dc'][0].T[live], want_dc[live])
    assert np.allclose(out['log10_fo'][0].T[live], want_fo[live])

    # the dead slot is NaN in every float column, and -1 in the index columns
    for key in flows_lib.CW_KEYS + flows_lib.PROV_KEYS:
        assert np.isnan(out[key][0, -1, -1]), f"{key} dead slot is not NaN"
    for key in flows_lib.IDX_KEYS:
        assert out[key][0, -1, -1] == -1, f"{key} dead slot is not -1"


def test_cw_columns_stalled_redshift_is_nan():
    """holodeck's -1 redshift sentinel must become NaN, never a negative distance."""
    R, K = 1, 2
    M, Q, Z, F = 2, 2, 2, 1
    mt = np.array([1e8, 1e9]) * MSOL
    mr = np.array([0.3, 0.9])
    redz = np.full((M, Q, Z, F), 0.5)
    redz[0, 0, 0, 0] = -1.0        # stalled
    fobs = np.array([1e-9])

    ranked = dict(
        hc=np.full((R, K), 1e-16),
        bidx=np.array([[0, 1]]),   # first source sits in the stalled cell
        fidx=np.zeros((R, K), dtype=int),
        lidx=np.zeros((R, K), dtype=int),
    )
    out = flows_lib.cw_columns(ranked, mt, mr, redz, fobs)
    assert np.isnan(out['log10_dc'][0, 0, 0]), "stalled bin did not become NaN"
    assert np.isfinite(out['log10_dc'][0, 1, 0]), "live bin was masked out"


# ==============================================================================
# ====    end-to-end    ====
# ==============================================================================


@pytest.fixture(scope='module')
def _small_model():
    from holodeck.librarian import param_spaces_classic as psc
    space = psc.PS_Classic_Phenom_Astro(holo.log, 4, (16, 17, 18), 1234)
    return space.model_for_params(space.param_dict(0))


def test_run_cws_reproducible(_small_model):
    """The same seed must give byte-identical output; different seeds must not."""
    sam, hard = _small_model
    cents, edges = flows_lib.flow_freqs(flows_lib.DEF_DF, 5)
    kw = dict(nreals=4, nloudest=3, nrank=3, log=holo.log)

    aa = flows_lib.run_cws(sam, hard, cents, edges, seed=7, **kw)
    bb = flows_lib.run_cws(sam, hard, cents, edges, seed=7, **kw)
    cc = flows_lib.run_cws(sam, hard, cents, edges, seed=8, **kw)

    for key in flows_lib.CW_KEYS:
        assert np.array_equal(aa[key], bb[key], equal_nan=True), f"{key} not reproducible"
    assert not all(
        np.array_equal(aa[key], cc[key], equal_nan=True) for key in flows_lib.CW_KEYS
    ), "different seeds gave identical output"


def test_run_cws_shapes_and_ranges(_small_model):
    """Output must have the documented shapes, and physically sane values."""
    sam, hard = _small_model
    nreals, nrank, nfreqs = 4, 3, 5
    cents, edges = flows_lib.flow_freqs(flows_lib.DEF_DF, nfreqs)
    data = flows_lib.run_cws(sam, hard, cents, edges, nreals=nreals, nloudest=3,
                             nrank=nrank, seed=7, log=holo.log)

    for key in flows_lib.CW_KEYS + flows_lib.PROV_KEYS + flows_lib.IDX_KEYS:
        assert data[key].shape == (1, nrank, nreals), f"{key}: {data[key].shape}"

    assert np.allclose(data['fobs_cents'], cents)
    live = data['cw_fidx'] >= 0
    assert live.any(), "no live sources at all"

    # sources are ordered loudest-first within each realization
    hc = data['cw_hc'][0]
    for rr in range(nreals):
        vals = hc[:, rr][np.isfinite(hc[:, rr])]
        assert np.all(np.diff(vals) <= 0), f"realization {rr} is not sorted loudest-first"

    # frequencies must be on the grid we asked for
    assert np.allclose(10.0**data['log10_fo'][0][live[0]], cents[data['cw_fidx'][0][live[0]]])


def test_run_cws_gwb_reconstruction(_small_model):
    """`hc_rest` plus the kept sources must add back up to the population total, exactly.

    `hc_rest` is defined as everything the library does NOT store as a CW: the sub-threshold
    background plus every per-bin loudest source that lost the across-band ranking.  So adding the
    kept sources back must recover the same total the population had.
    """
    sam, hard = _small_model
    nreals, nrank, nfreqs, nloudest = 4, 4, 5, 6
    cents, edges = flows_lib.flow_freqs(flows_lib.DEF_DF, nfreqs)
    data = flows_lib.run_cws(sam, hard, cents, edges, nreals=nreals, nloudest=nloudest,
                             nrank=nrank, seed=11, save_gwb=True, log=holo.log)

    assert data['hc_rest'].shape == (nfreqs, nreals)
    assert np.all(np.isfinite(data['hc_rest']))
    assert np.all(data['hc_rest'] >= 0.0)

    # re-accumulate the kept sources into their frequency bins
    fidx = data['cw_fidx'][0]            # (K, R)
    hcs = data['cw_hc'][0]
    live = fidx >= 0
    sel2 = np.zeros((nfreqs, nreals))
    r_ix = np.broadcast_to(np.arange(nreals)[np.newaxis, :], fidx.shape)
    np.add.at(sel2, (fidx[live], r_ix[live]), hcs[live]**2)
    total = data['hc_rest']**2 + sel2

    # the same population, recomputed from the same seed
    from holodeck import gravwaves
    from holodeck.sams import sam_cyutils
    redz_final, diff_num = sam_cyutils.dynamic_binary_number_at_fobs(
        cents / 2.0, sam, hard, holo.cosmo)
    grid = [sam.mtot, sam.mrat, sam.redz, edges / 2.0]
    number = sam_cyutils.integrate_differential_number_3dx1d(grid, diff_num)
    h2fdf = gravwaves.char_strain_sq_from_bin_edges_redz(grid, redz_final)
    hc2ss, _b, hc2rest = flows_lib.loudest_per_bin(
        number, h2fdf, nreals, nloudest, np.random.default_rng(11), totals=True)
    want = hc2rest + hc2ss.sum(axis=-1)

    assert np.allclose(total, want, rtol=1e-12), "hc_rest + kept sources != population total"


def test_flow_freqs_matches_pta_freqs():
    """The explicit grid must be numerically identical to the duration-derived one."""
    df, nfreqs = flows_lib.DEF_DF, 60
    cents, edges = flows_lib.flow_freqs(df, nfreqs)
    want_cents, want_edges = utils.pta_freqs(dur=1.0/df, num=nfreqs)
    assert np.allclose(cents, want_cents)
    assert np.allclose(edges, want_edges)
    # 4x finer than the standard PTA grid: every 4th bin lands on a real PTA frequency
    pta_cents, _ = utils.pta_freqs(dur=holo.librarian.DEF_PTA_DUR*YR, num=nfreqs // 4)
    assert np.allclose(cents[3::4], pta_cents)
